CREATE DATABASE [RoCALink]
USE [RoCALink]

CREATE TABLE Staff(
StaffID CHAR (5) PRIMARY KEY CHECK (StaffID LIKE 'ST[0-9][0-9][0-9]'),
StaffName VARCHAR(255) CHECK (LEN(StaffName) > 4) NOT NULL,
StaffEmail VARCHAR(255) CHECK (StaffEmail LIKE '%@rocalink.com') NOT NULL,
StaffPhone VARCHAR(255) CHECK (StaffPhone LIKE '08%') NOT NULL,
StaffGender VARCHAR (6) CHECK (StaffGender IN ('Male','Female')) NOT NULL,
StaffSalary INT CHECK(StaffSalary BETWEEN 100000 AND 10000000) NOT NULL,
)

CREATE TABLE Customer(
CustomerID CHAR (5) PRIMARY KEY CHECK (CustomerID LIKE 'CU[0-9][0-9][0-9]'),
CustomerName VARCHAR(255) CHECK (LEN(CustomerName) > 4) NOT NULL,
CustomerPhone VARCHAR (255) CHECK (CustomerPhone LIKE '08%') NOT NULL,
CustomerGender VARCHAR(255) CHECK (CustomerGender IN ('Male','Female')) NOT NULL,
CustomerEmail VARCHAR (255) CHECK (CustomerEmail LIKE'%@gmail.com') NOT NULL
)

CREATE TABLE [Transaction] (
TransactionID CHAR (5) PRIMARY KEY CHECK (TransactionID LIKE 'TR[0-9][0-9][0-9]'),
StaffID CHAR (5) FOREIGN KEY REFERENCES Staff(StaffID) ON UPDATE CASCADE ON DELETE CASCADE NOT NULL,
CustomerID CHAR(5) FOREIGN KEY REFERENCES Customer(CustomerID) ON UPDATE CASCADE ON DELETE CASCADE NOT NULL,
TransactionDate DATE NOT NULL
)

CREATE TABLE BikeType (
BikeTypeID CHAR (5) PRIMARY KEY CHECK (BikeTypeID LIKE 'BT[0-9][0-9][0-9]'),
BikeTypeName VARCHAR (255) NOT NULL
)

CREATE TABLE BikeBrand (
BikeBrandID CHAR (5) PRIMARY KEY CHECK (BikeBrandID LIKE 'BR[0-9][0-9][0-9]'),
BikeBrandName VARCHAR (255) NOT NULL,
BikeBrandDesc VARCHAR (255) NOT NULL,
BikeBrandWeb VARCHAR (255)  CHECK (BikeBrandWeb LIKE 'www.%') NOT NULL,
BikeBrandNationality VARCHAR(255) NOT NULL
)

CREATE TABLE GroupSet (
GroupSetID CHAR (5) PRIMARY KEY CHECK (GroupSetID LIKE'GR[0-9][0-9][0-9]'),
GroupSetName VARCHAR (255) NOT NULL,
GroupSetNumberofGears INT CHECK (GroupSetNumberofGears BETWEEN 4 AND 12) NOT NULL,
GroupSetWirelessCapability VARCHAR(255) CHECK (GroupSetWirelessCapability IN ('True','False')) NOT NULL,
)

CREATE TABLE Bike(
BikeID CHAR (5) PRIMARY KEY CHECK (BikeID LIKE 'BK[0-9][0-9][0-9]'),
BikeTypeID CHAR (5) FOREIGN KEY REFERENCES BikeType(BikeTypeID) ON UPDATE CASCADE ON DELETE CASCADE NOT NULL,
BikeBrandID CHAR (5) FOREIGN KEY REFERENCES BikeBrand(BikeBrandID) ON UPDATE CASCADE ON DELETE CASCADE NOT NULL,
GroupSetID CHAR (5)  FOREIGN KEY REFERENCES GroupSet(GroupSetID) ON UPDATE CASCADE ON DELETE CASCADE NOT NULL,
BikeName VARCHAR (255) NOT NULL,
BikePrice INT NOT NULL,
Qty INT NOT NULL
)

CREATE TABLE TransactionDetail(
TransactionID CHAR (5) FOREIGN KEY REFERENCES [Transaction](TransactionID) ON UPDATE CASCADE ON DELETE CASCADE,
BikeID CHAR(5) FOREIGN KEY REFERENCES Bike(BikeID) ON UPDATE CASCADE ON DELETE CASCADE NOT NULL,
TransactionQty INT NOT NULL
)